#!/bin/bash

make -C ./CV
make -C ./DritteSeite
make -C ./Enclosure
make -C ./Anschreiben
pdftk ./CV/cv.pdf ./DritteSeite/dritteSeite.pdf cat output ./Build/CV_Bewerbung_Julian_Mueller.pdf
cp ./Anschreiben/anschreiben.pdf ./Build/Anschreiben_Bewerbung_Julian_Mueller.pdf
cp ./Enclosure/enclosure.pdf ./Build/Anhang_Bewerbung_Julian_Mueller.pdf
